# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Countertype.create([{ name: 'Granite'}, { name: 'Marble'}, { name: 'Soapstone'}, { name: 'Wood'}, { name: 'Quartz'},
	{ name: 'Concrete'}])

Granitecolor.create( name: 'Absolute Black', url: 'https://s3.amazonaws.com/mijovate/granite/absolute_black.jpg')
Granitecolor.create( name: 'African Ivory', url: 'https://s3.amazonaws.com/mijovate/granite/african_ivory.jpg')
Granitecolor.create( name: 'African Rainbow', url: 'https://s3.amazonaws.com/mijovate/granite/african_rainbow.jpg')
Granitecolor.create( name: 'Alaska White', url: 'https://s3.amazonaws.com/mijovate/granite/Alaska+White-200x200.jpg')
Granitecolor.create( name: 'Almond Gold', url: 'https://s3.amazonaws.com/mijovate/granite/Almond+Gold-200x200.jpg')
Granitecolor.create( name: 'Almond Mauve', url: 'https://s3.amazonaws.com/mijovate/granite/Almond+Mauve-200x200.jpg')
Granitecolor.create( name: 'Alpine White', url: 'https://s3.amazonaws.com/mijovate/granite/Alpine+White-200x200.jpg')
Granitecolor.create( name: 'Amadeus', url: 'https://s3.amazonaws.com/mijovate/granite/Amadeus.jpg')
Granitecolor.create( name: 'Amber Yellow', url: 'https://s3.amazonaws.com/mijovate/granite/Amber+Yellow-200x200.jpg')
Granitecolor.create( name: 'Andino White', url: 'https://s3.amazonaws.com/mijovate/granite/Andino+White-200x200.jpg')
Granitecolor.create( name: 'Andromeda White', url: 'https://s3.amazonaws.com/mijovate/granite/andromeda-white-granite-200x200.jpg')
Granitecolor.create( name: 'Apollo Storm', url: 'https://s3.amazonaws.com/mijovate/granite/Apollo+Storm-200x200.jpg')
Granitecolor.create( name: 'Astoria', url: 'https://s3.amazonaws.com/mijovate/granite/Astoria.jpg')
Granitecolor.create( name: 'Autumn Beige', url: 'https://s3.amazonaws.com/mijovate/granite/Autumn+Beige-200x200.jpg')
Granitecolor.create( name: 'Azul Platino', url: 'https://s3.amazonaws.com/mijovate/granite/Azul+Platino-200x200.jpg')
Granitecolor.create( name: 'Azurite', url: 'https://s3.amazonaws.com/mijovate/granite/Azurite.jpg')
Granitecolor.create( name: 'Bain Brook Brown', url: 'https://s3.amazonaws.com/mijovate/granite/Bain+Brook+Brown-200x200.jpg')
Granitecolor.create( name: 'Baltic Brown', url: 'https://s3.amazonaws.com/mijovate/granite/Baltic+Brown-200x200.jpg')
Granitecolor.create( name: 'Barricato', url: 'https://s3.amazonaws.com/mijovate/granite/Barricato.jpg')
Granitecolor.create( name: 'Belvedere', url: 'https://s3.amazonaws.com/mijovate/granite/Belvedere_web-200x200.jpg')
Granitecolor.create( name: 'Betularie', url: 'https://s3.amazonaws.com/mijovate/granite/Betularie.jpg')
Granitecolor.create( name: 'Biano Antico', url: 'https://s3.amazonaws.com/mijovate/granite/Bianco+Antico-200x200.jpg')
Granitecolor.create( name: 'Black Galaxy', url: 'https://s3.amazonaws.com/mijovate/granite/Black+Galaxy-200x200.jpg')
Granitecolor.create( name: 'Black Pearl', url: 'https://s3.amazonaws.com/mijovate/granite/Black+Pearl-200x200.jpg')
Granitecolor.create( name: 'Blanco Perla', url: 'https://s3.amazonaws.com/mijovate/granite/Blanco+Perla-200x200.jpg')
Granitecolor.create( name: 'Blanco Taupe', url: 'https://s3.amazonaws.com/mijovate/granite/Blanco+Taupe-200x200.jpg')
Granitecolor.create( name: 'Blue Pearl Royal', url: 'https://s3.amazonaws.com/mijovate/granite/Blue+Pearl+Royal-200x200.jpg')
Granitecolor.create( name: 'Blue Pearl Silver', url: 'https://s3.amazonaws.com/mijovate/granite/Blue+Pearl+Silver-200x200.jpg')
Granitecolor.create( name: 'Blue Pearl', url: 'https://s3.amazonaws.com/mijovate/granite/Blue+Pearl-200x200.jpg')
Granitecolor.create( name: 'Blue Flower', url: 'https://s3.amazonaws.com/mijovate/granite/Blue-Flower-Granite-200x200.jpg')
Granitecolor.create( name: 'Bordeaux', url: 'https://s3.amazonaws.com/mijovate/granite/Bordeaux.jpg')
Granitecolor.create( name: 'Boreal', url: 'https://s3.amazonaws.com/mijovate/granite/Boreal.jpg')
Granitecolor.create( name: 'Brown Antique', url: 'https://s3.amazonaws.com/mijovate/granite/Brown+Antique-200x200.jpg')
Granitecolor.create( name: 'Brownie', url: 'https://s3.amazonaws.com/mijovate/granite/Brownie.jpg')
Granitecolor.create( name: 'Caledonia', url: 'https://s3.amazonaws.com/mijovate/granite/Caledonia.jpg')
Granitecolor.create( name: 'Caribbean Green', url: 'https://s3.amazonaws.com/mijovate/granite/Caribbean+Green-200x200.jpg')
Granitecolor.create( name: 'Carioca Gold', url: 'https://s3.amazonaws.com/mijovate/granite/Carioca+Gold-200x200.jpg')
Granitecolor.create( name: 'Carnaval', url: 'https://s3.amazonaws.com/mijovate/granite/Carnaval.jpg')
Granitecolor.create( name: 'Chocolate Bordeaux', url: 'https://s3.amazonaws.com/mijovate/granite/Chocolate+Bordeaux-200x200.jpg')
Granitecolor.create( name: 'Coffee Brown', url: 'https://s3.amazonaws.com/mijovate/granite/Coffee+Brown-200x200.jpg')
Granitecolor.create( name: 'Cold Spring', url: 'https://s3.amazonaws.com/mijovate/granite/Cold+Spring-200x200.jpg')
Granitecolor.create( name: 'Costa Esmeralda', url: 'https://s3.amazonaws.com/mijovate/granite/Costa+Esmeralda-200x200.jpg')
Granitecolor.create( name: 'Crema Atlantico', url: 'https://s3.amazonaws.com/mijovate/granite/Crema+Atlantico-200x200.jpg')
Granitecolor.create( name: 'Crema Bordeaux', url: 'https://s3.amazonaws.com/mijovate/granite/Crema+Bordeaux-200x200.jpg')
Granitecolor.create( name: 'Crema Caramel', url: 'https://s3.amazonaws.com/mijovate/granite/Crema+Caramel-200x200.jpg')
Granitecolor.create( name: 'Dakota Mahogany', url: 'https://s3.amazonaws.com/mijovate/granite/Dakota+Mahogany-200x200.jpg')
Granitecolor.create( name: 'Desert Brown', url: 'https://s3.amazonaws.com/mijovate/granite/Desert+Brown-200x200.jpg')
Granitecolor.create( name: 'Dynamic Blue', url: 'https://s3.amazonaws.com/mijovate/granite/Dynamic+Blue-200x200.jpg')
Granitecolor.create( name: 'Emerald Pearl', url: 'https://s3.amazonaws.com/mijovate/granite/Emerald+Pearl-200x200.jpg')
Granitecolor.create( name: 'Fire Bordeaux', url: 'https://s3.amazonaws.com/mijovate/granite/Fire+Bordeaux-200x200.jpg')
Granitecolor.create( name: 'Galaxy Bordeaux', url: 'https://s3.amazonaws.com/mijovate/granite/Galaxy+Bordeaux-200x200.jpg')
Granitecolor.create( name: 'Giallo Antico', url: 'https://s3.amazonaws.com/mijovate/granite/Giallo+Antico-200x200.jpg')
Granitecolor.create( name: 'Giallo Bahia', url: 'https://s3.amazonaws.com/mijovate/granite/Giallo+Bahia-200x200.jpg')
Granitecolor.create( name: 'Giallo Fantasia', url: 'https://s3.amazonaws.com/mijovate/granite/Giallo+Fantasia-200x200.jpg')
Granitecolor.create( name: 'Giallo Vicenza', url: 'https://s3.amazonaws.com/mijovate/granite/Giallo+Vicenza-200x200.jpg')
Granitecolor.create( name: 'Gibli', url: 'https://s3.amazonaws.com/mijovate/granite/Gibli.jpg')
Granitecolor.create( name: 'Golden Ripple', url: 'https://s3.amazonaws.com/mijovate/granite/Golden+Ripple-200x200.jpg')
Granitecolor.create( name: 'Golden Riviera', url: 'https://s3.amazonaws.com/mijovate/granite/Golden+Riviera-200x200.jpg')
Granitecolor.create( name: 'Golden Cascade', url: 'https://s3.amazonaws.com/mijovate/granite/Golden-Cascade-Granite-200x200.jpg')
Granitecolor.create( name: 'Hawaii', url: 'https://s3.amazonaws.com/mijovate/granite/Hawaii.jpg')
Granitecolor.create( name: 'Ice Blue', url: 'https://s3.amazonaws.com/mijovate/granite/Ice+Blue-200x200.jpg')
Granitecolor.create( name: 'Imperial Coffee', url: 'https://s3.amazonaws.com/mijovate/granite/Imperial+Coffee-200x200.jpg')
Granitecolor.create( name: 'Indian Dakota', url: 'https://s3.amazonaws.com/mijovate/granite/Indian+Dakota-200x200.jpg')
Granitecolor.create( name: 'Ipanema White', url: 'https://s3.amazonaws.com/mijovate/granite/Ipanema+White-200x200.jpg')
Granitecolor.create( name: 'Juparana Arandis', url: 'https://s3.amazonaws.com/mijovate/granite/Juparana+Arandis-200x200.jpg')
Granitecolor.create( name: 'Juparana Delicatus', url: 'https://s3.amazonaws.com/mijovate/granite/Juparana+Delicatus-200x200.jpg')
Granitecolor.create( name: 'Juparana Persia', url: 'https://s3.amazonaws.com/mijovate/granite/Juparana+Persia-200x200.jpg')
Granitecolor.create( name: 'Juparana Tier Ivory', url: 'https://s3.amazonaws.com/mijovate/granite/Juparana+Tier+Ivory-200x200.jpg')
Granitecolor.create( name: 'Juparana Tier', url: 'https://s3.amazonaws.com/mijovate/granite/Juparana+Tier-200x200.jpg')
Granitecolor.create( name: 'Kamarica', url: 'https://s3.amazonaws.com/mijovate/granite/Kamarica.jpg')
Granitecolor.create( name: 'Key West Gold', url: 'https://s3.amazonaws.com/mijovate/granite/Key+West+Gold-200x200.jpg')
Granitecolor.create( name: 'Lapidus', url: 'https://s3.amazonaws.com/mijovate/granite/Lapidus.jpg')
Granitecolor.create( name: 'Lennon', url: 'https://s3.amazonaws.com/mijovate/granite/Lennon.jpg')
Granitecolor.create( name: 'Luna Pearl', url: 'https://s3.amazonaws.com/mijovate/granite/Luna+Pearl-200x200.jpg')
Granitecolor.create( name: 'Mascarello', url: 'https://s3.amazonaws.com/mijovate/granite/Mascarello.jpg')
Granitecolor.create( name: 'Minsk Green', url: 'https://s3.amazonaws.com/mijovate/granite/minsk-green1-e1444497945337-200x200.jpg')
Granitecolor.create( name: 'Monte Cristo', url: 'https://s3.amazonaws.com/mijovate/granite/Monte+Cristo-200x200.jpg')
Granitecolor.create( name: 'Namibian Cream', url: 'https://s3.amazonaws.com/mijovate/granite/Namibian+Cream-200x200.jpg')
Granitecolor.create( name: 'Namibian Gold', url: 'https://s3.amazonaws.com/mijovate/granite/Namibian+Gold-200x200.jpg')
Granitecolor.create( name: 'Netuno Bordeaux', url: 'https://s3.amazonaws.com/mijovate/granite/Netuno+Bordeaux-200x200.jpg')
Granitecolor.create( name: 'New Giallo Fantasia', url: 'https://s3.amazonaws.com/mijovate/granite/New+Giallo+Fantasia-200x200.jpg')
Granitecolor.create( name: 'New Kashmir White', url: 'https://s3.amazonaws.com/mijovate/granite/New+Kashmir+White-200x200.jpg')
Granitecolor.create( name: 'New Venetian White', url: 'https://s3.amazonaws.com/mijovate/granite/New+Venetian+Gold-200x200.jpg')
Granitecolor.create( name: 'Normandy', url: 'https://s3.amazonaws.com/mijovate/granite/Normandy.jpg')
Granitecolor.create( name: 'Ornamental Dark', url: 'https://s3.amazonaws.com/mijovate/granite/Ornamental+Dark-200x200.jpg')
Granitecolor.create( name: 'Paradiso', url: 'https://s3.amazonaws.com/mijovate/granite/Paradiso-200x200.jpg')
Granitecolor.create( name: 'Peach Purse', url: 'https://s3.amazonaws.com/mijovate/granite/Peach+Purse-200x200.jpg')
Granitecolor.create( name: 'Peacock Green', url: 'https://s3.amazonaws.com/mijovate/granite/Peacock+Green-200x200.jpg')
Granitecolor.create( name: 'Premium Black', url: 'https://s3.amazonaws.com/mijovate/granite/Premium+Black-200x200.jpg')
Granitecolor.create( name: 'Premium Plus Black', url: 'https://s3.amazonaws.com/mijovate/granite/Premium+Plus+Black-200x200.jpg')
Granitecolor.create( name: 'River White', url: 'https://s3.amazonaws.com/mijovate/granite/River+White-200x200.jpg')
Granitecolor.create( name: 'Rosewood', url: 'https://s3.amazonaws.com/mijovate/granite/Rosewood.jpg')
Granitecolor.create( name: 'SF Real', url: 'https://s3.amazonaws.com/mijovate/granite/S-F-Real1-200x200.jpg')
Granitecolor.create( name: 'Safari Green', url: 'https://s3.amazonaws.com/mijovate/granite/Safari+Green-200x200.jpg')
Granitecolor.create( name: 'Santa Cecelia', url: 'https://s3.amazonaws.com/mijovate/granite/Santa+Cecelia-200x200.jpg')
Granitecolor.create( name: 'Santa Cecelia LC', url: 'https://s3.amazonaws.com/mijovate/granite/Santa+Cecilia+LC-200x200.jpg')
Granitecolor.create( name: 'Sapphire Blue', url: 'https://s3.amazonaws.com/mijovate/granite/Sapphire+Blue-200x200.jpg')
Granitecolor.create( name: 'Siberian White', url: 'https://s3.amazonaws.com/mijovate/granite/Siberian+White-200x200.jpg')
Granitecolor.create( name: 'Silver Cloud', url: 'https://s3.amazonaws.com/mijovate/granite/Silver+Cloud-200x200.jpg')
Granitecolor.create( name: 'Steel Grey', url: 'https://s3.amazonaws.com/mijovate/granite/Steel+Grey-200x200.jpg')
Granitecolor.create( name: 'Tahoe', url: 'https://s3.amazonaws.com/mijovate/granite/Tahoe.jpg')
Granitecolor.create( name: 'Tan Brown', url: 'https://s3.amazonaws.com/mijovate/granite/Tan+Brown-200x200.jpg')
Granitecolor.create( name: 'Tasmanian Green', url: 'https://s3.amazonaws.com/mijovate/granite/Tasmanian+Green-200x200.jpg')
Granitecolor.create( name: 'Toffee', url: 'https://s3.amazonaws.com/mijovate/granite/Toffee-200x200.jpg')
Granitecolor.create( name: 'Tropic Brown', url: 'https://s3.amazonaws.com/mijovate/granite/Tropic+Brown-200x200.jpg')
Granitecolor.create( name: 'Tropical Green', url: 'https://s3.amazonaws.com/mijovate/granite/Tropical+Green-200x200.jpg')
Granitecolor.create( name: 'Typhoon Green', url: 'https://s3.amazonaws.com/mijovate/granite/Typhoon+Green-200x200.jpg')
Granitecolor.create( name: 'Ubatuba', url: 'https://s3.amazonaws.com/mijovate/granite/Ubatuba.jpg')
Granitecolor.create( name: 'Venetian Ice', url: 'https://s3.amazonaws.com/mijovate/granite/Venetian+Ice-200x200.jpg')
Granitecolor.create( name: 'Verde Butterfly', url: 'https://s3.amazonaws.com/mijovate/granite/Verde+Butterfly-200x200.jpg')
Granitecolor.create( name: 'Virginia Mist', url: 'https://s3.amazonaws.com/mijovate/granite/Virginia+Mist-200x200.jpg')
Granitecolor.create( name: 'Volga Blue', url: 'https://s3.amazonaws.com/mijovate/granite/Volga+Blue-200x200.jpg')
Granitecolor.create( name: 'Vyara Gold', url: 'https://s3.amazonaws.com/mijovate/granite/Vyara+Gold-200x200.jpg')
Granitecolor.create( name: 'Vyara Juparana', url: 'https://s3.amazonaws.com/mijovate/granite/Vyara+Juparana-200x200.jpg')
Granitecolor.create( name: 'White Ice', url: 'https://s3.amazonaws.com/mijovate/granite/White+Ice-200x200.jpg')
Granitecolor.create( name: 'White Macaubus', url: 'https://s3.amazonaws.com/mijovate/granite/White+Macaubas-200x200.jpg')
Granitecolor.create( name: 'White Mist', url: 'https://s3.amazonaws.com/mijovate/granite/White+Mist-200x200.jpg')
Granitecolor.create( name: 'White Spring', url: 'https://s3.amazonaws.com/mijovate/granite/White+Spring-200x200.jpg')
Granitecolor.create( name: 'White Tango', url: 'https://s3.amazonaws.com/mijovate/granite/White+Tango-200x200.jpg')
Granitecolor.create( name: 'White Wave', url: 'https://s3.amazonaws.com/mijovate/granite/White+Wave-200x200.jpg')
Granitecolor.create( name: 'Wild Sea', url: 'https://s3.amazonaws.com/mijovate/granite/wild-sea-200x200.jpg')
Granitecolor.create( name: 'Yellow River', url: 'https://s3.amazonaws.com/mijovate/granite/Yellow+River-200x200.jpg')

Marblecolor.create( name: 'Antartide', url: 'https://s3.amazonaws.com/mijovate/marble/antartide.jpg')
Marblecolor.create( name: 'Arabescato Ventao', url: 'https://s3.amazonaws.com/mijovate/marble/arabescato_venato.jpg')
Marblecolor.create( name: 'Arabescus White', url: 'https://s3.amazonaws.com/mijovate/marble/Arabescus+White-200x200.jpg')
Marblecolor.create( name: 'Athens Grey', url: 'https://s3.amazonaws.com/mijovate/marble/Athens+Grey-200x200.jpg')
Marblecolor.create( name: 'Bianco Venatino', url: 'https://s3.amazonaws.com/mijovate/marble/Bianco+Venatino-200x200.jpg')
Marblecolor.create( name: 'Botticino Fiorito', url: 'https://s3.amazonaws.com/mijovate/marble/Botticino+Fiorito-200x200.jpg')
Marblecolor.create( name: 'Breccia Oniciata', url: 'https://s3.amazonaws.com/mijovate/marble/Breccia+Oniciata-200x200.jpg')
Marblecolor.create( name: 'Cafe Forest', url: 'https://s3.amazonaws.com/mijovate/marble/Cafe+Forest-200x200.jpg')
Marblecolor.create( name: 'Calacatta Carrara', url: 'https://s3.amazonaws.com/mijovate/marble/Calacatta+Carrara-200x200.jpg')
Marblecolor.create( name: 'Calacatta Gold Premium', url: 'https://s3.amazonaws.com/mijovate/marble/Calacatta+Gold+Premium-200x200.jpg')
Marblecolor.create( name: 'Calacatta Lasa', url: 'https://s3.amazonaws.com/mijovate/marble/Calacatta+Lasa-200x200.jpg')
Marblecolor.create( name: 'Calacatta Splendor', url: 'https://s3.amazonaws.com/mijovate/marble/Calacatta+Splendor-200x200.jpg')
Marblecolor.create( name: 'Calacatta Vagli', url: 'https://s3.amazonaws.com/mijovate/marble/Calacatta+Vagli-200x200.jpg')
Marblecolor.create( name: 'Calcutta Borgi', url: 'https://s3.amazonaws.com/mijovate/marble/Calcutta_Borgi_Crop-1-e1441079019247-200x200.jpg')
Marblecolor.create( name: 'Carrara White', url: 'https://s3.amazonaws.com/mijovate/marble/Carrara-White1-200x200.jpg')
Marblecolor.create( name: 'Carrara White C/D', url: 'https://s3.amazonaws.com/mijovate/marble/Carrara-White-C-D-Marble2-200x200.jpg')
Marblecolor.create( name: 'Crema Cappucino', url: 'https://s3.amazonaws.com/mijovate/marble/Crema+Cappuccino-200x200.jpg')
Marblecolor.create( name: 'Crema Marfil Classic', url: 'https://s3.amazonaws.com/mijovate/marble/Crema+Marfil+Classic-200x200.jpg')
Marblecolor.create( name: 'Crema Marfil Premium', url: 'https://s3.amazonaws.com/mijovate/marble/Crema+Marfil+Premium-200x200.jpg')
Marblecolor.create( name: 'Dark Green', url: 'https://s3.amazonaws.com/mijovate/marble/Dark+Green-200x200.jpg')
Marblecolor.create( name: 'Elegant White', url: 'https://s3.amazonaws.com/mijovate/marble/Elegant+White-200x200.jpg')
Marblecolor.create( name: 'Emperador Dark', url: 'https://s3.amazonaws.com/mijovate/marble/Emperador+Dark-200x200.jpg')
Marblecolor.create( name: 'Emperador Light', url: 'https://s3.amazonaws.com/mijovate/marble/Emperador+Light-200x200.jpg')
Marblecolor.create( name: 'Fantasy Brown', url: 'https://s3.amazonaws.com/mijovate/marble/Fantasy+Brown-200x200.jpg')
Marblecolor.create( name: 'Marmara White', url: 'https://s3.amazonaws.com/mijovate/marble/Marmara-White1-200x200.jpg')
Marblecolor.create( name: 'Nano Glass', url: 'https://s3.amazonaws.com/mijovate/marble/Nano+Glass+Slab-200x200.jpg')
Marblecolor.create( name: 'Paradise Blue', url: 'https://s3.amazonaws.com/mijovate/marble/Paradise_blue_close-web-200x200.jpg')
Marblecolor.create( name: 'Rain Forest', url: 'https://s3.amazonaws.com/mijovate/marble/Rain+Forest+Slab-200x200.jpg')
Marblecolor.create( name: 'Statuary Venato', url: 'https://s3.amazonaws.com/mijovate/marble/Statuary-Venato-Marble.jpg')
Marblecolor.create( name: 'Statueritto', url: 'https://s3.amazonaws.com/mijovate/marble/Statueritto-200x200.jpg')
Marblecolor.create( name: 'Super Thassos Glass', url: 'https://s3.amazonaws.com/mijovate/marble/Super-Thassos-Glass1-200x200.jpg')
Marblecolor.create( name: 'Thassos White Slab', url: 'https://s3.amazonaws.com/mijovate/marble/Thassos+White+Slab-200x200.jpg')
Marblecolor.create( name: 'Tundra Gray', url: 'https://s3.amazonaws.com/mijovate/marble/Tundra-Gray1-200x200.jpg')
Marblecolor.create( name: 'Volakas', url: 'https://s3.amazonaws.com/mijovate/marble/Volakas-200x200.jpg')
Marblecolor.create( name: 'White Oak', url: 'https://s3.amazonaws.com/mijovate/marble/White-Oak1-200x200.jpg')

